/* @generated by scripts/gen-english-routes.mjs */
import * as localePage from '../../../../[locale]/ops/demos/[demo]/page';
import { bindEnglish } from '@/lib/english-route';

const bound = bindEnglish(localePage as never);

export function generateStaticParams() {
  return bound.generateStaticParams();
}

export default function Page(props: { params: Promise<Record<string, string | string[]>> }) {
  return bound.Page(props);
}
