/* @generated by scripts/gen-english-routes.mjs */
import * as localePage from '../../../[locale]/ops/data/page';
import { bindEnglish } from '@/lib/english-route';

const bound = bindEnglish(localePage as never);

export default function Page(props: { params: Promise<Record<string, string | string[]>> }) {
  return bound.Page(props);
}
